export const data: Array<{
  id: number;
  date: string;
  locationLink: string;
  realmFlagSrc: string;
  realmName: string;
  challengersFaction: string;
  challengerName: string;
  challengerClass: string;
  opponentName: string;
  opponentClass: string;
  victory: string;
  rule: string;
  comment: string;
}> = [
  {
    "id": 1,
    "date": "January 1, 2023 at 00:00 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=",
    "realmFlagSrc": "usaFlag",
    "realmName": "Defias Pillager",
    "challengersFaction": "horde",
    "challengerName": "Orbb",
    "challengerClass": "hunter",
    "opponentName": "Yespfizer",
    "opponentClass": "mage",
    "victory": "Death",
    "rule": "Buffs Allowed",
    "comment": "Ready to duel, or are you crafting tea?",
  },
  {
    "id": 2,
    "date": "Febuary 1, 2023 at 00:00 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=",
    "realmFlagSrc": "europeFlag",
    "realmName": "Stitches",
    "challengersFaction": "alliance",
    "challengerName": "JohnDoe",
    "challengerClass": "hunter",
    "opponentName": "JaneRoe",
    "opponentClass": "hunter",
    "victory": "Forfeit",
    "rule": "Buffs Allowed",
    "comment": "Put down that fishing rod; we've got destiny!",
  },
  {
    "id": 3,
    "date": "September 1, 2023 at 00:00 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=",
    "realmFlagSrc": "koreaFlag",
    "realmName": "Voidwalker",
    "challengersFaction": "horde",
    "challengerName": "Joe",
    "challengerClass": "priest",
    "opponentName": "Joey",
    "opponentClass": "shaman",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "Potions won't save you from my skills!",
  },
  {
    "id": 4,
    "date": "April 15, 2023 at 08:30 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-444444",
    "realmFlagSrc": "taiwanFlag",
    "realmName": "Hogger",
    "challengersFaction": "alliance",
    "challengerName": "Alice",
    "challengerClass": "hunter",
    "opponentName": "Bob",
    "opponentClass": "mage",
    "victory": "Forfeit",
    "rule": "Buffs Allowed",
    "comment": "Hope your gear's repaired; you'll need it!",
  },
  {
    "id": 5,
    "date": "May 20, 2023 at 10:15 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-555555",
    "realmFlagSrc": "usaFlag",
    "realmName": "Defias Pillager",
    "challengersFaction": "horde",
    "challengerName": "Charlie",
    "challengerClass": "priest",
    "opponentName": "David",
    "opponentClass": "warlock",
    "victory": "Forfeit",
    "rule": "Buffs Allowed",
    "comment": "High noon duel? Nah, Stranglethorn settles!",
  },
  {
    "id": 6,
    "date": "June 5, 2023 at 14:45 PM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-666666",
    "realmFlagSrc": "europeFlag",
    "realmName": "Nek'Rosh",
    "challengersFaction": "alliance",
    "challengerName": "Eve",
    "challengerClass": "hunter",
    "opponentName": "Frank",
    "opponentClass": "druid",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "Grab your sword; time to dance with death!",
  },
  {
    "id": 7,
    "date": "July 10, 2023 at 16:30 PM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-777777",
    "realmFlagSrc": "taiwanFlag",
    "realmName": "Hogger",
    "challengersFaction": "horde",
    "challengerName": "Grace",
    "challengerClass": "hunter",
    "opponentName": "Henry",
    "opponentClass": "warrior",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "Meet in Arathi Basin; loser buys first ale!",
  },
  {
    "id": 8,
    "date": "August 12, 2023 at 18:20 PM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-888888",
    "realmFlagSrc": "koreaFlag",
    "realmName": "Teremus",
    "challengersFaction": "alliance",
    "challengerName": "Isaac",
    "challengerClass": "shaman",
    "opponentName": "Jessica",
    "opponentClass": "priest",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "One winner, one loser; lots of broken gear.",
  },
  {
    "id": 9,
    "date": "October 22, 2023 at 20:10 PM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-999999",
    "realmFlagSrc": "usaFlag",
    "realmName": "Defias Pillager",
    "challengersFaction": "horde",
    "challengerName": "Kevin",
    "challengerClass": "shaman",
    "opponentName": "Laura",
    "opponentClass": "mage",
    "victory": "Forfeit",
    "rule": "Buffs Allowed",
    "comment": "Bring spells; I'll bring the pain!",
  },
  {
    "id": 10,
    "date": "November 30, 2023 at 22:00 PM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-101010",
    "realmFlagSrc": "europeFlag",
    "realmName": "Nek'Rosh",
    "challengersFaction": "alliance",
    "challengerName": "Michael",
    "challengerClass": "priest",
    "opponentName": "Nancy",
    "opponentClass": "shaman",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "My grandma hits harder; be embarrassed!",
  },
  {
    "id": 11,
    "date": "December 5, 2023 at 23:45 PM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-111000",
    "realmFlagSrc": "taiwanFlag",
    "realmName": "Hogger",
    "challengersFaction": "horde",
    "challengerName": "Oliver",
    "challengerClass": "paladin",
    "opponentName": "Patricia",
    "opponentClass": "hunter",
    "victory": "Forfeit",
    "rule": "Buffs Allowed",
    "comment": "If I win, rename your character 'Chicken'.",
  },
  {
    "id": 12,
    "date": "January 12, 2023 at 01:30 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-121212",
    "realmFlagSrc": "koreaFlag",
    "realmName": "Voidwalker",
    "challengersFaction": "alliance",
    "challengerName": "Quincy",
    "challengerClass": "paladin",
    "opponentName": "Rachel",
    "opponentClass": "mage",
    "victory": "Death",
    "rule": "Buffs Allowed",
    "comment": "Duel in Ironforge? Guards feeling generous?",
  },
  {
    "id": 13,
    "date": "February 18, 2023 at 02:15 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-131313",
    "realmFlagSrc": "usaFlag",
    "realmName": "Defias Pillager",
    "challengersFaction": "horde",
    "challengerName": "Sam",
    "challengerClass": "warlock",
    "opponentName": "Sarah",
    "opponentClass": "mage",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "Prepare your eulogy; healer awaits!",
  },
  {
    "id": 14,
    "date": "March 24, 2023 at 03:45 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-141414",
    "realmFlagSrc": "europeFlag",
    "realmName": "Stitches",
    "challengersFaction": "alliance",
    "challengerName": "Tom",
    "challengerClass": "warrior",
    "opponentName": "Tina",
    "opponentClass": "warlock",
    "victory": "Death",
    "rule": "No Buffs",
    "comment": "Don't cry when you lose; it's just a virtual death.",
  },
  {
    "id": 15,
    "date": "April 8, 2023 at 04:30 AM PDT",
    "locationLink": "https://www.wowhead.com/maps?data=-151515",
    "realmFlagSrc": "taiwanFlag",
    "realmName": "Hogger",
    "challengersFaction": "horde",
    "challengerName": "Ursula",
    "challengerClass": "hunter",
    "opponentName": "Victor",
    "opponentClass": "druid",
    "victory": "Death",
    "rule": "Buffs Allowed",
    "comment": "Last chance to chicken out; or 'Blood Elf' out?",
  },
];